import { createSlice, type PayloadAction } from "@reduxjs/toolkit"
import type { Customer, CRMState } from "./crmTypes"

export const CRM_STORAGE_KEY = "aethel_ebms_crm"

const getInitialState = (): CRMState => {
  if (typeof window === "undefined") {
    return { customers: [] }
  }
  const stored = window.localStorage.getItem(CRM_STORAGE_KEY)
  if (stored) {
    try {
      return { customers: JSON.parse(stored) }
    } catch (e) {
      console.error("Failed to parse CRM from localStorage", e)
    }
  }

  // Generate 20 realistic companies
  const mockCustomers: Customer[] = [
    {
      id: "CUST-1001",
      companyName: "Acme Corp",
      contactPerson: "John Doe",
      email: "john.doe@acmecorp.com",
      phone: "+1 (555) 123-4567",
      industry: "Manufacturing",
      website: "https://acmecorp.com",
      address: "123 Factory Blvd",
      city: "Detroit",
      country: "USA",
      status: "Active Client",
      assignedEmployeeId: "EMP-001",
      assignedEmployeeName: "Alice Smith",
      notes: "Long term client, highly reliable.",
      createdAt: "2023-01-15T08:00:00Z",
    },
    {
      id: "CUST-1002",
      companyName: "TechNova Solutions",
      contactPerson: "Jane Roe",
      email: "jane.roe@technova.io",
      phone: "+1 (555) 987-6543",
      industry: "Technology",
      website: "https://technova.io",
      address: "456 Innovation Way",
      city: "San Francisco",
      country: "USA",
      status: "Lead",
      assignedEmployeeId: "EMP-002",
      assignedEmployeeName: "Bob Jones",
      notes: "Met at the tech conference in SF. Promising lead.",
      createdAt: "2023-11-05T14:30:00Z",
    },
    {
      id: "CUST-1003",
      companyName: "Global Logistics",
      contactPerson: "Sam Brown",
      email: "s.brown@globallogistics.com",
      phone: "+44 20 7946 0958",
      industry: "Transportation",
      website: "https://globallogistics.com",
      address: "789 Trade St",
      city: "London",
      country: "UK",
      status: "Negotiation",
      assignedEmployeeId: "EMP-001",
      assignedEmployeeName: "Alice Smith",
      notes: "Discussing pricing for Q3 deployment.",
      createdAt: "2023-08-20T10:15:00Z",
    },
    {
      id: "CUST-1004",
      companyName: "FinHealth Partners",
      contactPerson: "Lisa White",
      email: "lisa.white@finhealth.org",
      phone: "+1 (555) 234-5678",
      industry: "Healthcare",
      website: "https://finhealth.org",
      address: "101 Medical Center Dr",
      city: "Boston",
      country: "USA",
      status: "Contacted",
      assignedEmployeeId: "EMP-003",
      assignedEmployeeName: "Charlie Brown",
      notes: "Sent introductory email and brochure.",
      createdAt: "2023-12-01T09:00:00Z",
    },
    {
      id: "CUST-1005",
      companyName: "EcoBuild Group",
      contactPerson: "Mark Green",
      email: "m.green@ecobuild.com",
      phone: "+61 2 9876 5432",
      industry: "Construction",
      website: "https://ecobuild.com",
      address: "202 Sustainable Ave",
      city: "Sydney",
      country: "Australia",
      status: "Active Client",
      assignedEmployeeId: "EMP-002",
      assignedEmployeeName: "Bob Jones",
      notes: "Using our software for their new projects.",
      createdAt: "2022-05-10T11:45:00Z",
    },
    {
      id: "CUST-1006",
      companyName: "Retail Giants",
      contactPerson: "Sarah Connor",
      email: "s.connor@retailgiants.com",
      phone: "+1 (555) 345-6789",
      industry: "Retail",
      website: "https://retailgiants.com",
      address: "303 Market St",
      city: "New York",
      country: "USA",
      status: "Inactive",
      assignedEmployeeId: "EMP-004",
      assignedEmployeeName: "Diana Prince",
      notes: "Contract not renewed due to budget cuts.",
      createdAt: "2021-09-01T08:30:00Z",
    },
    {
      id: "CUST-1007",
      companyName: "AgriCorp",
      contactPerson: "David Smith",
      email: "d.smith@agricorp.com",
      phone: "+1 (555) 456-7890",
      industry: "Agriculture",
      website: "https://agricorp.com",
      address: "404 Farm Rd",
      city: "Omaha",
      country: "USA",
      status: "Lead",
      assignedEmployeeId: "EMP-001",
      assignedEmployeeName: "Alice Smith",
      notes: "Interested in our data analytics tool.",
      createdAt: "2023-12-10T15:20:00Z",
    },
    {
      id: "CUST-1008",
      companyName: "EduTech Hub",
      contactPerson: "Rachel Adams",
      email: "rachel@edutechhub.edu",
      phone: "+1 (555) 567-8901",
      industry: "Education",
      website: "https://edutechhub.edu",
      address: "505 University Blvd",
      city: "Austin",
      country: "USA",
      status: "Negotiation",
      assignedEmployeeId: "EMP-003",
      assignedEmployeeName: "Charlie Brown",
      notes: "Awaiting approval from the board.",
      createdAt: "2023-11-15T13:00:00Z",
    },
    {
      id: "CUST-1009",
      companyName: "Energy Solutions",
      contactPerson: "Tom Baker",
      email: "t.baker@energysol.com",
      phone: "+49 30 123456",
      industry: "Energy",
      website: "https://energysol.com",
      address: "606 Power St",
      city: "Berlin",
      country: "Germany",
      status: "Active Client",
      assignedEmployeeId: "EMP-005",
      assignedEmployeeName: "Eve Davis",
      notes: "Renewed contract for another 3 years.",
      createdAt: "2020-03-12T09:30:00Z",
    },
    {
      id: "CUST-1010",
      companyName: "Media Works",
      contactPerson: "Emily Clark",
      email: "e.clark@mediaworks.net",
      phone: "+1 (555) 678-9012",
      industry: "Media",
      website: "https://mediaworks.net",
      address: "707 Studio Ave",
      city: "Los Angeles",
      country: "USA",
      status: "Contacted",
      assignedEmployeeId: "EMP-002",
      assignedEmployeeName: "Bob Jones",
      notes: "Follow up next week after their busy season.",
      createdAt: "2023-12-05T10:45:00Z",
    },
    {
      id: "CUST-1011",
      companyName: "Auto Dynamics",
      contactPerson: "Kevin Lewis",
      email: "k.lewis@autodynamics.com",
      phone: "+81 3 1234 5678",
      industry: "Automotive",
      website: "https://autodynamics.com",
      address: "808 Motor Pkwy",
      city: "Tokyo",
      country: "Japan",
      status: "Lead",
      assignedEmployeeId: "EMP-004",
      assignedEmployeeName: "Diana Prince",
      notes: "Needs integration with their CRM.",
      createdAt: "2023-12-20T16:00:00Z",
    },
    {
      id: "CUST-1012",
      companyName: "Blue Ocean Finance",
      contactPerson: "Nancy Taylor",
      email: "n.taylor@blueocean.fi",
      phone: "+44 161 123 4567",
      industry: "Finance",
      website: "https://blueocean.fi",
      address: "909 Bank St",
      city: "Manchester",
      country: "UK",
      status: "Active Client",
      assignedEmployeeId: "EMP-001",
      assignedEmployeeName: "Alice Smith",
      notes: "Key account, quarterly reviews required.",
      createdAt: "2021-11-22T11:15:00Z",
    },
    {
      id: "CUST-1013",
      companyName: "Urban Design Co",
      contactPerson: "Brian Moore",
      email: "brian@urbandesign.co",
      phone: "+1 (555) 789-0123",
      industry: "Architecture",
      website: "https://urbandesign.co",
      address: "111 Design Ave",
      city: "Chicago",
      country: "USA",
      status: "Negotiation",
      assignedEmployeeId: "EMP-003",
      assignedEmployeeName: "Charlie Brown",
      notes: "Finalizing license numbers.",
      createdAt: "2023-10-18T14:20:00Z",
    },
    {
      id: "CUST-1014",
      companyName: "HealthFirst Clinics",
      contactPerson: "Dr. Amanda White",
      email: "awhite@healthfirst.org",
      phone: "+1 (555) 890-1234",
      industry: "Healthcare",
      website: "https://healthfirst.org",
      address: "222 Wellness Blvd",
      city: "Seattle",
      country: "USA",
      status: "Contacted",
      assignedEmployeeId: "EMP-005",
      assignedEmployeeName: "Eve Davis",
      notes: "Interested in the enterprise plan.",
      createdAt: "2023-12-28T09:10:00Z",
    },
    {
      id: "CUST-1015",
      companyName: "NextGen Software",
      contactPerson: "Jason Lee",
      email: "jason.lee@nextgen.io",
      phone: "+1 (555) 901-2345",
      industry: "Technology",
      website: "https://nextgen.io",
      address: "333 Code St",
      city: "San Jose",
      country: "USA",
      status: "Active Client",
      assignedEmployeeId: "EMP-002",
      assignedEmployeeName: "Bob Jones",
      notes: "Strong partnership, potential for upselling.",
      createdAt: "2022-02-14T15:30:00Z",
    },
    {
      id: "CUST-1016",
      companyName: "Global Foods",
      contactPerson: "Maria Garcia",
      email: "m.garcia@globalfoods.com",
      phone: "+34 91 123 4567",
      industry: "Food & Beverage",
      website: "https://globalfoods.com",
      address: "444 Culinary Way",
      city: "Madrid",
      country: "Spain",
      status: "Inactive",
      assignedEmployeeId: "EMP-004",
      assignedEmployeeName: "Diana Prince",
      notes: "Switched to a competitor.",
      createdAt: "2020-07-09T10:00:00Z",
    },
    {
      id: "CUST-1017",
      companyName: "SkyHigh Airlines",
      contactPerson: "Chris Martin",
      email: "cmartin@skyhigh.aero",
      phone: "+1 (555) 012-3456",
      industry: "Aviation",
      website: "https://skyhigh.aero",
      address: "555 Terminal Way",
      city: "Denver",
      country: "USA",
      status: "Lead",
      assignedEmployeeId: "EMP-001",
      assignedEmployeeName: "Alice Smith",
      notes: "Inquired via website form.",
      createdAt: "2023-12-25T11:55:00Z",
    },
    {
      id: "CUST-1018",
      companyName: "Solid State Properties",
      contactPerson: "Jessica Wong",
      email: "j.wong@solidstate.com",
      phone: "+65 6123 4567",
      industry: "Real Estate",
      website: "https://solidstate.com",
      address: "666 Tower Rd",
      city: "Singapore",
      country: "Singapore",
      status: "Negotiation",
      assignedEmployeeId: "EMP-003",
      assignedEmployeeName: "Charlie Brown",
      notes: "Reviewing legal terms.",
      createdAt: "2023-11-28T14:40:00Z",
    },
    {
      id: "CUST-1019",
      companyName: "Quantum Computing",
      contactPerson: "Robert Black",
      email: "r.black@quantum.tech",
      phone: "+1 (555) 123-9876",
      industry: "Technology",
      website: "https://quantum.tech",
      address: "777 Future St",
      city: "Boston",
      country: "USA",
      status: "Active Client",
      assignedEmployeeId: "EMP-005",
      assignedEmployeeName: "Eve Davis",
      notes: "Beta testing the new release.",
      createdAt: "2022-08-05T09:20:00Z",
    },
    {
      id: "CUST-1020",
      companyName: "Green Planet Charities",
      contactPerson: "Anna Bell",
      email: "anna@greenplanet.org",
      phone: "+1 (555) 234-8765",
      industry: "Non-Profit",
      website: "https://greenplanet.org",
      address: "888 Charity Ave",
      city: "Portland",
      country: "USA",
      status: "Contacted",
      assignedEmployeeId: "EMP-002",
      assignedEmployeeName: "Bob Jones",
      notes: "Requested a demo for next week.",
      createdAt: "2023-12-29T13:15:00Z",
    },
  ]

  return { customers: mockCustomers }
}

const crmSlice = createSlice({
  name: "crm",
  initialState: getInitialState(),
  reducers: {
    addCustomer: (state, action: PayloadAction<Customer>) => {
      state.customers.push(action.payload)
    },
    updateCustomer: (state, action: PayloadAction<Customer>) => {
      const index = state.customers.findIndex((c) => c.id === action.payload.id)
      if (index !== -1) {
        state.customers[index] = action.payload
      }
    },
    deleteCustomer: (state, action: PayloadAction<string>) => {
      state.customers = state.customers.filter((c) => c.id !== action.payload)
    },
    updateCustomerStatus: (
      state,
      action: PayloadAction<{ id: string; status: Customer["status"] }>
    ) => {
      const customer = state.customers.find((c) => c.id === action.payload.id)
      if (customer) {
        customer.status = action.payload.status
      }
    },
  },
})

export const { addCustomer, updateCustomer, deleteCustomer, updateCustomerStatus } =
  crmSlice.actions

export default crmSlice.reducer
