import { createSlice, type PayloadAction } from "@reduxjs/toolkit"
import type { Asset, AssetsState } from "./assetTypes"

export const ASSETS_STORAGE_KEY = "aethel_ebms_assets"

const getInitialState = (): AssetsState => {
  if (typeof window === "undefined") {
    return { assets: [] }
  }
  const stored = window.localStorage.getItem(ASSETS_STORAGE_KEY)
  if (stored) {
    try {
      return { assets: JSON.parse(stored) }
    } catch (e) {
      console.error("Failed to parse Assets from localStorage", e)
    }
  }

  const currentDate = new Date()
  const currentYear = currentDate.getFullYear()

  // Generate mock assets
  const mockAssets: Asset[] = [
    {
      id: "AST-1001",
      assetCode: "LPT-001",
      assetName: "MacBook Pro 16\"",
      category: "Laptop",
      brand: "Apple",
      model: "MacBook Pro 16\" M3 Max",
      serialNumber: "C02XYZ123ABC",
      purchaseDate: new Date(currentYear - 1, 5, 15).toISOString(),
      purchasePrice: 2499,
      warrantyExpiry: new Date(currentYear + 2, 5, 15).toISOString(),
      assignedEmployeeId: "EMP-101",
      assignedEmployeeName: "Sarah Jenkins",
      status: "Assigned",
      location: "Headquarters - Floor 3",
      notes: "Primary development machine",
    },
    {
      id: "AST-1002",
      assetCode: "LPT-002",
      assetName: "Dell XPS 15",
      category: "Laptop",
      brand: "Dell",
      model: "XPS 15 9530",
      serialNumber: "DELL456789",
      purchaseDate: new Date(currentYear - 1, 3, 20).toISOString(),
      purchasePrice: 1899,
      warrantyExpiry: new Date(currentYear + 2, 3, 20).toISOString(),
      assignedEmployeeId: "EMP-102",
      assignedEmployeeName: "Michael Chen",
      status: "Assigned",
      location: "Headquarters - Floor 2",
      notes: "Engineering lead device",
    },
    {
      id: "AST-1003",
      assetCode: "LPT-003",
      assetName: "ThinkPad X1 Carbon",
      category: "Laptop",
      brand: "Lenovo",
      model: "ThinkPad X1 Carbon Gen 11",
      serialNumber: "LEN987654",
      purchaseDate: new Date(currentYear - 1, 8, 10).toISOString(),
      purchasePrice: 1650,
      warrantyExpiry: new Date(currentYear + 2, 8, 10).toISOString(),
      assignedEmployeeId: "EMP-103",
      assignedEmployeeName: "Sophia Miller",
      status: "Assigned",
      location: "Remote",
      notes: "Remote work setup",
    },
    {
      id: "AST-1004",
      assetCode: "LPT-004",
      assetName: "HP Spectre x360",
      category: "Laptop",
      brand: "HP",
      model: "Spectre x360 14",
      serialNumber: "HP12345678",
      purchaseDate: new Date(currentYear - 1, 10, 5).toISOString(),
      purchasePrice: 1399,
      warrantyExpiry: new Date(currentYear + 2, 10, 5).toISOString(),
      status: "Available",
      location: "IT Storage - Room A",
      notes: "Spare device for new hires",
    },
    {
      id: "AST-1005",
      assetCode: "LPT-005",
      assetName: "MacBook Air M2",
      category: "Laptop",
      brand: "Apple",
      model: "MacBook Air 13\" M2",
      serialNumber: "C02ABC987DEF",
      purchaseDate: new Date(currentYear - 1, 11, 1).toISOString(),
      purchasePrice: 1199,
      warrantyExpiry: new Date(currentYear + 2, 11, 1).toISOString(),
      assignedEmployeeId: "EMP-104",
      assignedEmployeeName: "Robert Frost",
      status: "Assigned",
      location: "Headquarters - Floor 4",
      notes: "Design team device",
    },
    {
      id: "AST-1006",
      assetCode: "DSK-001",
      assetName: "iMac 24\"",
      category: "Desktop",
      brand: "Apple",
      model: "iMac 24\" M3",
      serialNumber: "C02IMAC123",
      purchaseDate: new Date(currentYear - 1, 6, 15).toISOString(),
      purchasePrice: 1499,
      warrantyExpiry: new Date(currentYear + 2, 6, 15).toISOString(),
      status: "Available",
      location: "Design Studio",
      notes: "Creative workstation",
    },
    {
      id: "AST-1007",
      assetCode: "DSK-002",
      assetName: "OptiPlex 7090",
      category: "Desktop",
      brand: "Dell",
      model: "OptiPlex 7090 Tower",
      serialNumber: "DESK789012",
      purchaseDate: new Date(currentYear - 1, 4, 20).toISOString(),
      purchasePrice: 899,
      warrantyExpiry: new Date(currentYear + 2, 4, 20).toISOString(),
      assignedEmployeeId: "EMP-105",
      assignedEmployeeName: "David Vance",
      status: "Assigned",
      location: "Headquarters - Floor 2",
      notes: "Finance department",
    },
    {
      id: "AST-1008",
      assetCode: "DSK-003",
      assetName: "Mac Studio",
      category: "Desktop",
      brand: "Apple",
      model: "Mac Studio M2 Ultra",
      serialNumber: "C02STUDIO456",
      purchaseDate: new Date(currentYear - 1, 7, 1).toISOString(),
      purchasePrice: 3999,
      warrantyExpiry: new Date(currentYear + 2, 7, 1).toISOString(),
      status: "Assigned",
      location: "Video Production Room",
      notes: "High-performance rendering",
    },
    {
      id: "AST-1009",
      assetCode: "MON-001",
      assetName: "UltraSharp 32\"",
      category: "Monitor",
      brand: "Dell",
      model: "UltraSharp U3223QE",
      serialNumber: "MON321654",
      purchaseDate: new Date(currentYear - 1, 5, 10).toISOString(),
      purchasePrice: 699,
      warrantyExpiry: new Date(currentYear + 2, 5, 10).toISOString(),
      assignedEmployeeId: "EMP-101",
      assignedEmployeeName: "Sarah Jenkins",
      status: "Assigned",
      location: "Headquarters - Floor 3",
      notes: "4K display for development",
    },
    {
      id: "AST-1010",
      assetCode: "MON-002",
      assetName: "Pro Display XDR",
      category: "Monitor",
      brand: "Apple",
      model: "Pro Display XDR",
      serialNumber: "C02XDR789",
      purchaseDate: new Date(currentYear - 1, 9, 15).toISOString(),
      purchasePrice: 4999,
      warrantyExpiry: new Date(currentYear + 2, 9, 15).toISOString(),
      status: "Available",
      location: "Design Studio",
      notes: "Color-critical work",
    },
    {
      id: "AST-1011",
      assetCode: "MON-003",
      assetName: "LG UltraFine 5K",
      category: "Monitor",
      brand: "LG",
      model: "UltraFine 5K 27MD5KL-B",
      serialNumber: "LG5K12345",
      purchaseDate: new Date(currentYear - 1, 8, 20).toISOString(),
      purchasePrice: 1299,
      warrantyExpiry: new Date(currentYear + 2, 8, 20).toISOString(),
      assignedEmployeeId: "EMP-103",
      assignedEmployeeName: "Sophia Miller",
      status: "Assigned",
      location: "Remote",
      notes: "Remote work monitor",
    },
    {
      id: "AST-1012",
      assetCode: "MON-004",
      assetName: "Samsung Odyssey G9",
      category: "Monitor",
      brand: "Samsung",
      model: "Odyssey G9 49\"",
      serialNumber: "SAMG96789",
      purchaseDate: new Date(currentYear - 1, 12, 1).toISOString(),
      purchasePrice: 1499,
      warrantyExpiry: new Date(currentYear + 2, 12, 1).toISOString(),
      status: "Available",
      location: "Gaming/Testing Lab",
      notes: "Ultrawide for testing",
    },
    {
      id: "AST-1013",
      assetCode: "KBD-001",
      assetName: "Magic Keyboard",
      category: "Keyboard",
      brand: "Apple",
      model: "Magic Keyboard with Touch ID",
      serialNumber: "KBDAPPLE01",
      purchaseDate: new Date(currentYear - 1, 6, 15).toISOString(),
      purchasePrice: 199,
      warrantyExpiry: new Date(currentYear + 2, 6, 15).toISOString(),
      status: "Available",
      location: "IT Storage - Room B",
      notes: "Spare keyboard",
    },
    {
      id: "AST-1014",
      assetCode: "KBD-002",
      assetName: "Keychron Q1",
      category: "Keyboard",
      brand: "Keychron",
      model: "Q1 Pro",
      serialNumber: "KBDQ12345",
      purchaseDate: new Date(currentYear - 1, 7, 20).toISOString(),
      purchasePrice: 199,
      warrantyExpiry: new Date(currentYear + 2, 7, 20).toISOString(),
      assignedEmployeeId: "EMP-102",
      assignedEmployeeName: "Michael Chen",
      status: "Assigned",
      location: "Headquarters - Floor 2",
      notes: "Mechanical keyboard",
    },
    {
      id: "AST-1015",
      assetCode: "MOU-001",
      assetName: "Magic Mouse",
      category: "Mouse",
      brand: "Apple",
      model: "Magic Mouse 2",
      serialNumber: "MOUAPPLE01",
      purchaseDate: new Date(currentYear - 1, 6, 15).toISOString(),
      purchasePrice: 99,
      warrantyExpiry: new Date(currentYear + 2, 6, 15).toISOString(),
      status: "Available",
      location: "IT Storage - Room B",
      notes: "Spare mouse",
    },
    {
      id: "AST-1016",
      assetCode: "MOU-002",
      assetName: "MX Master 3S",
      category: "Mouse",
      brand: "Logitech",
      model: "MX Master 3S",
      serialNumber: "LOGMX67890",
      purchaseDate: new Date(currentYear - 1, 7, 20).toISOString(),
      purchasePrice: 99,
      warrantyExpiry: new Date(currentYear + 2, 7, 20).toISOString(),
      assignedEmployeeId: "EMP-102",
      assignedEmployeeName: "Michael Chen",
      status: "Assigned",
      location: "Headquarters - Floor 2",
      notes: "Ergonomic mouse",
    },
    {
      id: "AST-1017",
      assetCode: "PHN-001",
      assetName: "iPhone 15 Pro Max",
      category: "Phone",
      brand: "Apple",
      model: "iPhone 15 Pro Max 256GB",
      serialNumber: "IPHONE123ABC",
      purchaseDate: new Date(currentYear - 1, 9, 20).toISOString(),
      purchasePrice: 1199,
      warrantyExpiry: new Date(currentYear + 2, 9, 20).toISOString(),
      assignedEmployeeId: "EMP-106",
      assignedEmployeeName: "Emily Blunt",
      status: "Assigned",
      location: "Headquarters - Floor 5",
      notes: "Executive phone",
    },
    {
      id: "AST-1018",
      assetCode: "PHN-002",
      assetName: "Samsung Galaxy S24",
      category: "Phone",
      brand: "Samsung",
      model: "Galaxy S24 Ultra",
      serialNumber: "SAMGAL456DEF",
      purchaseDate: new Date(currentYear - 1, 10, 15).toISOString(),
      purchasePrice: 1299,
      warrantyExpiry: new Date(currentYear + 2, 10, 15).toISOString(),
      status: "Available",
      location: "IT Storage - Room C",
      notes: "Spare device",
    },
    {
      id: "AST-1019",
      assetCode: "PRN-001",
      assetName: "LaserJet Pro",
      category: "Printer",
      brand: "HP",
      model: "LaserJet Pro M404dn",
      serialNumber: "PRNHP789012",
      purchaseDate: new Date(currentYear - 1, 4, 10).toISOString(),
      purchasePrice: 299,
      warrantyExpiry: new Date(currentYear + 2, 4, 10).toISOString(),
      status: "Available",
      location: "Headquarters - Floor 1",
      notes: "Main office printer",
    },
    {
      id: "AST-1020",
      assetCode: "PRN-002",
      assetName: "ImageRunner",
      category: "Printer",
      brand: "Canon",
      model: "imageRUNNER 1435iF",
      serialNumber: "PRNCAN345678",
      purchaseDate: new Date(currentYear - 1, 5, 5).toISOString(),
      purchasePrice: 899,
      warrantyExpiry: new Date(currentYear + 2, 5, 5).toISOString(),
      status: "Maintenance",
      location: "Headquarters - Floor 1",
      notes: "Needs roller replacement",
    },
    {
      id: "AST-1021",
      assetCode: "FRN-001",
      assetName: "Aeron Chair",
      category: "Furniture",
      brand: "Herman Miller",
      model: "Aeron Chair Size B",
      serialNumber: "HMAER901234",
      purchaseDate: new Date(currentYear - 2, 3, 15).toISOString(),
      purchasePrice: 1495,
      warrantyExpiry: new Date(currentYear + 10, 3, 15).toISOString(),
      assignedEmployeeId: "EMP-107",
      assignedEmployeeName: "Marcus Aurelius",
      status: "Assigned",
      location: "Headquarters - Floor 3",
      notes: "Executive seating",
    },
    {
      id: "AST-1022",
      assetCode: "FRN-002",
      assetName: "Standing Desk",
      category: "Furniture",
      brand: "Uplift",
      model: "V2 Standing Desk",
      serialNumber: "UPV2567890",
      purchaseDate: new Date(currentYear - 1, 8, 1).toISOString(),
      purchasePrice: 699,
      warrantyExpiry: new Date(currentYear + 10, 8, 1).toISOString(),
      assignedEmployeeId: "EMP-101",
      assignedEmployeeName: "Sarah Jenkins",
      status: "Assigned",
      location: "Headquarters - Floor 3",
      notes: "Height-adjustable desk",
    },
    {
      id: "AST-1023",
      assetCode: "FRN-003",
      assetName: "Embody Chair",
      category: "Furniture",
      brand: "Herman Miller",
      model: "Embody Chair",
      serialNumber: "HMEMB345678",
      purchaseDate: new Date(currentYear - 2, 6, 20).toISOString(),
      purchasePrice: 1595,
      warrantyExpiry: new Date(currentYear + 10, 6, 20).toISOString(),
      status: "Available",
      location: "IT Storage - Room D",
      notes: "Spare ergonomic chair",
    },
    {
      id: "AST-1024",
      assetCode: "LPT-006",
      assetName: "Surface Laptop 5",
      category: "Laptop",
      brand: "Microsoft",
      model: "Surface Laptop 5",
      serialNumber: "MSFT789012",
      purchaseDate: new Date(currentYear - 2, 2, 10).toISOString(),
      purchasePrice: 1299,
      warrantyExpiry: new Date(currentYear - 1, 2, 10).toISOString(),
      status: "Retired",
      location: "Archive Storage",
      notes: "End of life - replaced",
    },
    {
      id: "AST-1025",
      assetCode: "DSK-004",
      assetName: "Precision 7960",
      category: "Desktop",
      brand: "Dell",
      model: "Precision 7960 Tower",
      serialNumber: "PREC567890",
      purchaseDate: new Date(currentYear - 1, 11, 15).toISOString(),
      purchasePrice: 5499,
      warrantyExpiry: new Date(currentYear + 2, 11, 15).toISOString(),
      status: "Maintenance",
      location: "IT Workshop",
      notes: "GPU upgrade in progress",
    },
    {
      id: "AST-1026",
      assetCode: "MON-005",
      assetName: "C27F398",
      category: "Monitor",
      brand: "LG",
      model: "27UK850-W",
      serialNumber: "LG4K67890",
      purchaseDate: new Date(currentYear - 1, 9, 1).toISOString(),
      purchasePrice: 499,
      warrantyExpiry: new Date(currentYear + 2, 9, 1).toISOString(),
      assignedEmployeeId: "EMP-105",
      assignedEmployeeName: "David Vance",
      status: "Assigned",
      location: "Headquarters - Floor 2",
      notes: "Finance department monitor",
    },
    {
      id: "AST-1027",
      assetCode: "KBD-003",
      assetName: "K840",
      category: "Keyboard",
      brand: "Logitech",
      model: "K840 Mechanical",
      serialNumber: "LOGK84012",
      purchaseDate: new Date(currentYear - 1, 10, 10).toISOString(),
      purchasePrice: 79,
      warrantyExpiry: new Date(currentYear + 2, 10, 10).toISOString(),
      status: "Available",
      location: "IT Storage - Room B",
      notes: "Budget mechanical keyboard",
    },
    {
      id: "AST-1028",
      assetCode: "MOU-003",
      assetName: "MX Anywhere 3",
      category: "Mouse",
      brand: "Logitech",
      model: "MX Anywhere 3",
      serialNumber: "LOGMXA345",
      purchaseDate: new Date(currentYear - 1, 11, 5).toISOString(),
      purchasePrice: 79,
      warrantyExpiry: new Date(currentYear + 2, 11, 5).toISOString(),
      assignedEmployeeId: "EMP-106",
      assignedEmployeeName: "Emily Blunt",
      status: "Assigned",
      location: "Headquarters - Floor 5",
      notes: "Portable mouse",
    },
    {
      id: "AST-1029",
      assetCode: "PHN-003",
      assetName: "Pixel 8 Pro",
      category: "Phone",
      brand: "Google",
      model: "Pixel 8 Pro 256GB",
      serialNumber: "GOOPIX789",
      purchaseDate: new Date(currentYear - 1, 12, 10).toISOString(),
      purchasePrice: 999,
      warrantyExpiry: new Date(currentYear + 2, 12, 10).toISOString(),
      status: "Available",
      location: "IT Storage - Room C",
      notes: "Android test device",
    },
    {
      id: "AST-1030",
      assetCode: "OTH-001",
      assetName: "iPad Pro 12.9\"",
      category: "Other",
      brand: "Apple",
      model: "iPad Pro 12.9\" M2",
      serialNumber: "C02IPAD123",
      purchaseDate: new Date(currentYear - 1, 8, 15).toISOString(),
      purchasePrice: 1099,
      warrantyExpiry: new Date(currentYear + 2, 8, 15).toISOString(),
      assignedEmployeeId: "EMP-107",
      assignedEmployeeName: "Marcus Aurelius",
      status: "Assigned",
      location: "Headquarters - Floor 3",
      notes: "Executive tablet",
    },
  ]

  return { assets: mockAssets }
}

const assetSlice = createSlice({
  name: "assets",
  initialState: getInitialState(),
  reducers: {
    addAsset: (state, action: PayloadAction<Asset>) => {
      state.assets.push(action.payload)
    },
    updateAsset: (state, action: PayloadAction<Asset>) => {
      const index = state.assets.findIndex((a) => a.id === action.payload.id)
      if (index !== -1) {
        state.assets[index] = action.payload
      }
    },
    deleteAsset: (state, action: PayloadAction<string>) => {
      state.assets = state.assets.filter((a) => a.id !== action.payload)
    },
    assignAsset: (
      state,
      action: PayloadAction<{ assetId: string; employeeId: string; employeeName: string }>
    ) => {
      const asset = state.assets.find((a) => a.id === action.payload.assetId)
      if (asset && (asset.status === "Available" || asset.status === "Assigned")) {
        asset.assignedEmployeeId = action.payload.employeeId
        asset.assignedEmployeeName = action.payload.employeeName
        asset.status = "Assigned"
      }
    },
    unassignAsset: (state, action: PayloadAction<string>) => {
      const asset = state.assets.find((a) => a.id === action.payload)
      if (asset) {
        asset.assignedEmployeeId = undefined
        asset.assignedEmployeeName = undefined
        asset.status = "Available"
      }
    },
  },
})

export const { addAsset, updateAsset, deleteAsset, assignAsset, unassignAsset } = assetSlice.actions

export default assetSlice.reducer
